from typing import Protocol


class LLMProvider(Protocol):
    @property
    def model(self) -> str: ...

    def complete_json(self, system: str, user: str, schema: dict | None = None) -> dict: ...

    def complete_text(self, system: str, user: str) -> str: ...

    def complete_vision(self, prompt: str, image_b64: str) -> str: ...
